# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  fcp-cv-frontend:
    build:
      target: development
    command: npm run dev
    ports:
      - '3000:3000'
    volumes:
      - ./app:/home/node/app
      - ./scripts:/home/node/scripts
      - ./package.json:/home/node/package.json
