# This override file should be used when running tests in CI pipelines
# to run tests against app code from the Docker image without binding
# ports to the host machine.

services:
  fcp-cv-frontend:
    build:
      target: development
    image: fcp-cv-frontend-development
    pull_policy: build
    command: npm run test
    environment:
      NODE_ENV: test
